# Generated by Django 3.2.4 on 2021-06-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamblog', '0002_rename_writepost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_date',
        ),
    ]
