# Generated by Django 3.2.4 on 2021-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamblog', '0003_rename_created_post_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
